release:
  github:
    owner: kulack
    name: pet
  name_template: '{{.Tag}}'
brews:
  -
    tap:
      owner: kulack
      name: homebrew-pet-kulack
    commit_author:
      name: goreleaserbot
      email: goreleaser@carlosbecker.com
    description: "Simple command-line snippet manager (fork by Kulack)"
    homepage: "https://github.com/kulack/pet"
    dependencies:
      - fzf
    install: |
      bin.install Dir['pet']
      zsh_completion.install "misc/completions/zsh/_pet"
    test: |
      system "#{bin}/pet"
builds:
- goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm
  - arm64
  - "386"
  goarm:
  - "6"
  main: .
  ldflags: -s -w -X github.com/kulack/pet/cmd.version={{.Version}}
archives:
  -
    format: tar.gz
    name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{
      .Arm }}{{ end }}'
    files:
    - LICENSE*
    - README*
    - CHANGELOG*
    - misc/completions/zsh/_pet
nfpms:
  -
    homepage: https://github.com/kulack/pet
    maintainer: Fred Kulack <kulack@gmail.com>
    description: "Simple command-line snippet manager (fork by Kulack)"
    bindir: /usr/local/bin
    license: MIT
    formats:
    - deb
    - rpm
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
