name: Privileged
description: You were directed from Github discussions to create an issue in Pet 👇
body:
  - type: markdown
    attributes:
      value: |
        ## Thanks!
        Thanks for your interest in Pet! 🚀
        If you are were not directed to create an issue here, please start the conversation in a [Question in GitHub Discussions](https://github.com/kulack/pet/discussions/categories/questions) instead!
        
        ## Got a PR?
        If you want to create a PR, share the idea first in [Github discussions](https://github.com/kulack/pet/discussions)! 💬
        This will give you ⚡️ quick feedback ⚡️ before you've spent time on it, instead of waiting for a much longer review process AFTER you've done the work.
  - type: checkboxes
    id: privileged
    attributes:
      label: Privileged issue
      description: Confirm that you were directed to create an issue here.
      options:
        - label: I've been directed through Discussions to create an issue here.
          required: true
  - type: textarea
    id: content
    attributes:
      label: Issue Content
      description: Add the content of the issue here.
